### ISSUE TITLE
Sync is stuck 

### ISSUE THREAD

**Issue by jianocid3** [guyzyl/whatsapp-contact-sync#157]
I have tried multiple times before deciding to raise this issue.

On my first try, over 100+ contacts were synced and did not progress further after hours.

On my most recent attempt, it has been stuck at 47 contacts for over 4 hours.

Other attempts were mainly trouble loading the WA QR code (it either didn't load or took very long to load), and if it did sync, it doesn't go past 20 contacts.

My attempt got to finish the sync. But i don't know how to delete/close this issue. Sorry!

**Comment by guyzyl** [comment]
Thanks for opening the issue!
I'm not sure what's causing it, I'll try to find the root cause of this.

FYI, if the syncing doesn't move for a few minutes, it probably crashed/failed for some reason and won't continue further so there's not need to wait for hours.

**Comment by guyzyl** [comment]
I've just tried it myself and everything worked as expected
![image](https://github.com/guyzyl/whatsapp-contact-sync/assets/3015856/59c5cf47-8620-4b76-83bf-d06a3e723ef6)

What probably happened is that while you were syncing, the server crashed due to a different reason causing your session to get destroyed.
Can you please try to sync again, and if you're not able to sync all the way comment here the time (and timezone) it got stuck?

**Comment by jianocid3** [comment]
I tried the sync again, and it successfully updated all my contacts with no issue.

I believe the previous issues were because the laptop went to sleep from being idle, causing the sync to hang.

**Comment by guyzyl** [comment]
@jianocid3 that's probably it, the syncing process stops if the connection to the servers is disconnected.
That's on purpose so there's a way to stop the syncing.
What probably happened is that your laptop went to sleep, causing the tab to disconnect from the server therefore stopping the syncing process.

I'm glad it worked now!
