### ISSUE TITLE
Whasync.com Google Sign In Issue "Something Went Wrong"

### ISSUE THREAD

**Issue by iman-hussain** [guyzyl/whatsapp-contact-sync#174]
As described in the title - WhatsApp appears to sync okay, but once I try to click on the correct google email it says "Something Went Wrong" really quickly.

Not entirely sure what's going on or if anyone else is experiencing this. Tried it on Chrome (already signed in) and Arc (already signed in).

I attempted chrome in an Incognito window and it wouldn't get past the WhatsApp Authorize stage after scanning the QR code.

Any further questions please ask - hopefully we can get this fixed.

**Comment by guyzyl** [comment]
When you got the something went wrong error, was it on whasync or in the google login tab?

**Comment by iman-hussain** [comment]
It was in the google login tab - I have two accounts to select and when I select the one I want I get the "something went wrong error" - will try it again today on a different WiFi network incase there's some sort of security issue.

**Comment by guyzyl** [comment]
I just tried to login myself and everything worked as expected, that means that the general GAuth flow works.
Since the error is from the Google Auth screen, it means it has to do something with your Google account / login, and it's not really possible for me to debug that (since it's on their end).

What I do recommend you check is that:
- Use Google login at a different website to make sure your account works properly
- You gave the proper permissions to whasync.com (didn't press deny while logging in)

Let me know once you check these, hopefully this will help locate the issue.

**Comment by iman-hussain** [comment]
Just tested it in incognito mode and works.
Would it be possible to have a server load stat somewhere - might help with people wondering why it's taking so long.
And for transparency reasons - a reminder to deauth whatsapp once the website is done.

**Comment by guyzyl** [comment]
Did you change anything from your end? Or did it just suddenly work.
I don't have those stats right now, but that's a good idea.

In regards to transparency, the access tokens get deleted from the backend automatically after a max of 30 minutes of inactivity.
A few issues were previously opened to automatically log out users, I tried that and the API that's available didn't work.
There's an open [issue](#36) to add a message explaining how to log out when the sync is complete, haven't gotten around to it yet.

**Comment by iman-hussain** [comment]
I don't think I changed anything - I think it was just a combination of trying again at a time that was less busy and using incognito mode (incase there was something interfering in my extensions).

If there are any way of getting logs I'd be happy to share.

Great work! Thanks :)
