### ISSUE TITLE
Nothing happens after scanning QR code

### ISSUE THREAD

**Issue by ChrisLahaye** [guyzyl/whatsapp-contact-sync#42]
Hello,

I wanted to let you know that nothing happens for me after scanning the QR code from the "Linked devices" screen. I am using the latest Whatsapp version on Android and tried whasync.com on both Firefox and Chrome. The console and network tab don't show any error or relevant information of what is going wrong.

Thank you!

**Comment by guyzyl** [comment]
At what time was that? So I can check the logs and see if anything happened.
If you don't have the timestamp, can you please try again and record it?

Also, did you see anything interesting in the console log?

**Comment by ChrisLahaye** [comment]
@guyzyl I just tried it again but unfortunately with the same result. This was around around 10:15 UTC, 8 March 2023. Nothing interesting in the logs. There is a single call to /api/status before showing the QR code and a websocket message from /api/ws for type whatsapp_qr. After scanning the QR code from my mobile the device gets added to Whatsapp but on the web app nothing happens.

**Comment by guyzyl** [comment]
I was able to replicate the issue both on whasync.com and locally, and found the problem.
The problem is that WhatsApp constantly changes their web API which causes whatsapp-web.js to break. That means that frequent updates to whatsapp-web.js is needed.

I've update the library in #43 which should fix the issue. @ChrisLahaye can you check if it works for you now?
I've also went ahead and opened #44 so this type of issues won't (hopefully) occur again in the future.

**Comment by ChrisLahaye** [comment]
@guyzyl I just managed to sync so it is fixed now. Thank you!

**Comment by guyzyl** [comment]
@ChrisLahaye glad I could help 😁
